### ISSUE TITLE
Run from qBittorrent directly

### ISSUE THREAD

**Issue by Fietspomp86** [Jorman/Scripts#17] opened 2023-06-10 23:38 UTC
Hi,

Thanks for your work, works well from Radarr etcetera.

Question though, there is also an option inside qBittorrent to execute a script when a torrent is added.
(Under Options -> Downloads -> Run External Program)
Now I've tried adding the script there, with the -n argument and %N (Torrent name), however this does not seem to work.
In the logs I see script is executed but no trackers are added.

It looks like this now:

**/path/to/script/AddqBittorrentTrackers.sh -n "%N"**

I'm running qBittorrent via docker container on Linux by the way.
When I see the log, it does say execute command **/path/to/script/AddqBittorrentTrackers.sh -n "TORRENT NAME"**,
but nothing happens.
When I bash inside the docker container and copy-paste the command, it does work.
Now I'm wondering if it is maybe the -n argument which is preventing it from working, but this is just a wild guess.

I have also tried to put it like this:
**/path/to/script/AddqBittorrentTrackers.sh -a**
But this also does not work.

Would it be possible to check from your side if this can be debugged?
I would be more than happy to help of course!

**Comment by denniskrol** [comment] 2023-06-13 03:31
Could this be related to an issue that I have?
I try to run `AddqBittorrentTrackers.sh -a` every 15 minutes from a cronjob from within an Ubuntu VM. When I run the command manually it works fine, and updates all the trackers on all my torrents. When I run this from a cronjob it always outputs 'No torrents found, exiting'. No matter what options I give the script. Even without options (which should show the help) it outputs 'No torrents found, exiting'. Its almost if it thinks it gets an option that it shouldn't get.

**Comment by neoKushan** [comment] 2023-09-05 17:19
So I've just stumbled upon the same issue @Fietspomp86 and @denniskrol  has and went around a wild-goose-chase trying to figure out what was going on. 

The script has a fatal flaw in its design that will prevent its use in qBitTorrent without modifications. The gist is this line [here](https://github.com/Jorman/Scripts/blob/a1f023c4f880ee3990b5755603c4663748f2a2ea/AddqBittorrentTrackers.sh#L184C15-L184C17) checks if the script is outputting to a terminal and if it is, will go through the usual steps of processing the input arguments and doing its work.

The catch is if it's not attached to a terminal it does something completely different, assuming only that its being called from one of the hardcoded *arrs and skips over all of the normal argument handling. This is why the script seems to work when you run it manually yourself or via sshing into a docker container or whatever - because it's connected to a terminal.

I've hacked apart the script to remove the if/else at that point and to always do the input argument handling (effectively breaking the *arr integration but it makes far more sense to me to do it in qBitTorrent directly anyway), if anyone wants my hacked apart script it's here - https://gist.github.com/neoKushan/0d87dac0e462f2abba7da664cd514c5d

@Jorman you're probably better at bash than I am and I think running the script from qBittorrent directly is a valid use-case - It'd be appreciated if you could update your script to accommodate for it. I'd submit a PR for it, but I haven't a clue what I am doing with linux most of the time.

**Comment by Jorman** [comment] 2023-09-07 22:04
Hi to all, I just update the script in order to work even with qBittorrent script functionality, but let me spend some time to reply to you all:
The original scope of the script was different, if I remember correctly I request this function to some qBittorrent guys in 2018 :) not bad! Btw, the main goal for the script is to inject trackers for all *arr and/or add trackers manually.
Now the new possibility added open a new way, potentially useless for *arr users but maybe useful for all users that use qBittorrent in a manual way.
For me the best is to have different scripts, the version for *arr users and the one for the "manual" ones but I agree that is possible that sometimes some pure *arr users can manually add torrent and don't want to manually open a terminal and inject trackers inside the torrent just added.
**Please note that now, with the new version if the script is used inside *arr program, the script will be executed two times, one from *arr and one from qBittorrent side too, not a big deal but you've to know that.** At this point is possible to remove the script execution from *arr side

@Fietspomp86 
Now you can set the script inside qBittorrent with the same form you already tried so
`/path/to/script/AddqBittorrentTrackers.sh -n "%N"`

@denniskrol 
Yes is related but note that now is working for qBittorrent docker version and not cron, maybe is possible to add but I don't have checked yet.
Please note that what your're trying to do is pretty much useless and potentially you will end in a infinite loop.
If you use the script as is, you inject about 150 trackers (depending on public lists) and most of the list is update every day, not every 15min.
If you run the script every 15min and your torrent list is huge is possible that on the very next run the 1st run is not done so you will start a new cycle and the previous one is not complete.
Only for your reference, I use the opposite logic, I use the hardlink checker to remove bad trackers, to speed up the client and optimize the memory usage.

@neoKushan 
Is not a fatal flaw error, is the way I want to use the script, manual or from *arr, is not a bug is intentional, but like I said I added a possibility to run, always automatically" from qBittorrent after adding a torrent, but remember that will be executed 2 times if one *arr will add torrent.
Like I said the origial script was different also because the qBittorrent functionality did not exist, now is different yes, but I've to maintain the compatibility with old qBittorrent release too.

Anyway I'll update the Readme to reflect this new possibility

**Comment by Jorman** [comment] 2023-09-08 17:33
Fixed with
https://github.com/Jorman/Scripts/commit/0d8c36083a1b1bc3704da3572016d5e03884d494

**Closed by Jorman** 2023-09-08 17:33 UTC

**Comment by neoKushan** [comment] 2023-09-08 22:34
Hey @Jorman , I just wanted to say thank you for taking the time to not only respond here but also to update the script to accommodate our use case. I hope no offence was taken by the "Fatal flaw" comment I made, it certainly wasn't intended as a criticism of you or your work and if it did come across that way, I apologise.

**Comment by denniskrol** [comment] 2023-09-09 03:31
@Jorman 
My logic for running it every 15 minutes (that might be a bit much, I agree) is that I add most torrents via RSS feeds, and I need to use a proxy to connect to the trackers. That proxy only works with HTTP trackers, and most public torrents only have UDP trackers by default, so I just get a bunch of 'stalled' torrents.

**Comment by Fietspomp86** [comment] 2023-09-09 06:36
@Jorman , thanks very much!

Using qbittorrent-nox docker container, I added JQ using a dockerfile.
Some torrents it doesn't recognize, I get the error that `There was no torrent found with text ""`
So now I've just changed the script parameters to -a, so that it'll at to all torrents upon adding one.
Since I don't have so many torrents active, it's not a big deal to me.
It seems this happens with torrents with special characters in their name, like { }.

**Comment by Jorman** [comment] 2023-09-09 17:13
@neoKushan 
Don't worry, you didn't offend me, I just wanted to better specify the mechanisms of the script

@denniskrol
Ok, mine was only curiosity, is not my business but why to all torrent every time? Btw, now you can remove the cron and use the script to inject every time one torrent was added

@Fietspomp86 
Yes, this's another reason why I prefer the manual way, and is not so hard if you think, when you add manually a torrent you can open a terminal and run the script :), you never fail because you can use only a part of the name and I'm sure this always works, in fact if you notice on the *arr mode I don't use the name but the hash and never have problem. I'll try something in order to "solve" this, but I've to make some test
